name: Auto test

on:
  push:
    branches: main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.17.0"

      - name: Git preparation
        run: |
          git config user.email "test@test.com"
          git config user.name "Test"

      - name: Unit-tests
        run: go test -v >> $GITHUB_STEP_SUMMARY